backend:
  name: git-gateway
  branch: main 

media_folder: "images/uploads" 

collections: 
  - name: "post" 
    label: "Post Product" 
    folder: "_posts" 
    sort: "date:desc" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Categories", name: "tags", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: Image, name: image, widget: image, required: true}
      - {label: Image, name: img, widget: image, required: true}
      - {label: Price, name: price, widget: number, required: true}
      - {label: Diskon, name: diskon, widget: number, required: false}
      - {label: Warna, name: warna, widget: string, required: true}
      - {label: Model, name: model, widget: string, required: true}
      - {label: Stok, name: stok, widget: number, required: true}
      - {label: Rate, name: rate, widget: number, required: true}
      - {label: RC, name: rC, widget: number, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}

    meta: 
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "blogpost" 
    label: "Blog Post" 
    folder: "blog"
    create: true
    slug: '{{title}}'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blogpost"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: Image, name: image, widget: image, required: true}

  - name: "blog" 
    label: "Blog Data" 
    folder: "_data"
    format: yml
    extension: yml
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true} 
      - {label: Deskripsi, name: deskripsi, widget: string, required: true} 
      - {label: Thumbnail, name: image, widget: image, required: true}
      - {label: URL, name: url, widget: string, required: true} 
